// ═══════════════════════════════════════════════════════════════
// FitOptim AI — Exercise Database
// Muscle groups, equipment, difficulty, calories burned per minute
// ═══════════════════════════════════════════════════════════════
export const EXERCISE_DB = [
  // ── COMPOUND LIFTS ──────────────────────────────────────────
  { name:'Barbell Squat', category:'compound', muscles:['quads','glutes','core'], equipment:'gym', difficulty:'intermediate', calPerMin:8 },
  { name:'Deadlift', category:'compound', muscles:['back','glutes','hamstrings'], equipment:'gym', difficulty:'intermediate', calPerMin:9 },
  { name:'Bench Press', category:'compound', muscles:['chest','triceps','shoulders'], equipment:'gym', difficulty:'intermediate', calPerMin:7 },
  { name:'Overhead Press', category:'compound', muscles:['shoulders','triceps','core'], equipment:'gym', difficulty:'intermediate', calPerMin:6 },
  { name:'Barbell Row', category:'compound', muscles:['back','biceps'], equipment:'gym', difficulty:'intermediate', calPerMin:7 },
  { name:'Romanian Deadlift', category:'compound', muscles:['hamstrings','glutes','back'], equipment:'gym', difficulty:'intermediate', calPerMin:7 },
  { name:'Front Squat', category:'compound', muscles:['quads','core','shoulders'], equipment:'gym', difficulty:'advanced', calPerMin:8 },
  { name:'Incline Bench Press', category:'compound', muscles:['chest','shoulders','triceps'], equipment:'gym', difficulty:'intermediate', calPerMin:6 },
  { name:'Leg Press', category:'compound', muscles:['quads','glutes'], equipment:'gym', difficulty:'beginner', calPerMin:7 },
  { name:'Lat Pulldown', category:'compound', muscles:['back','biceps'], equipment:'gym', difficulty:'beginner', calPerMin:5 },
  { name:'Cable Row', category:'compound', muscles:['back','biceps','core'], equipment:'gym', difficulty:'beginner', calPerMin:5 },
  { name:'Goblet Squat', category:'compound', muscles:['quads','glutes','core'], equipment:'dumbbell', difficulty:'beginner', calPerMin:7 },
  { name:'Dumbbell Bench Press', category:'compound', muscles:['chest','triceps'], equipment:'dumbbell', difficulty:'beginner', calPerMin:6 },
  { name:'Dumbbell Shoulder Press', category:'compound', muscles:['shoulders','triceps'], equipment:'dumbbell', difficulty:'beginner', calPerMin:5 },
  { name:'Dumbbell Lunge', category:'compound', muscles:['quads','glutes','hamstrings'], equipment:'dumbbell', difficulty:'beginner', calPerMin:7 },

  // ── ISOLATION ───────────────────────────────────────────────
  { name:'Bicep Curls', category:'isolation', muscles:['biceps'], equipment:'dumbbell', difficulty:'beginner', calPerMin:4 },
  { name:'Tricep Pushdown', category:'isolation', muscles:['triceps'], equipment:'gym', difficulty:'beginner', calPerMin:4 },
  { name:'Lateral Raises', category:'isolation', muscles:['shoulders'], equipment:'dumbbell', difficulty:'beginner', calPerMin:4 },
  { name:'Leg Curls', category:'isolation', muscles:['hamstrings'], equipment:'gym', difficulty:'beginner', calPerMin:5 },
  { name:'Leg Extension', category:'isolation', muscles:['quads'], equipment:'gym', difficulty:'beginner', calPerMin:5 },
  { name:'Face Pulls', category:'isolation', muscles:['shoulders','back'], equipment:'gym', difficulty:'beginner', calPerMin:4 },
  { name:'Calf Raises', category:'isolation', muscles:['calves'], equipment:'gym', difficulty:'beginner', calPerMin:4 },
  { name:'Hammer Curls', category:'isolation', muscles:['biceps'], equipment:'dumbbell', difficulty:'beginner', calPerMin:4 },
  { name:'Skull Crushers', category:'isolation', muscles:['triceps'], equipment:'gym', difficulty:'intermediate', calPerMin:4 },
  { name:'Cable Flyes', category:'isolation', muscles:['chest'], equipment:'gym', difficulty:'beginner', calPerMin:4 },
  { name:'Reverse Flyes', category:'isolation', muscles:['shoulders','back'], equipment:'dumbbell', difficulty:'beginner', calPerMin:3 },
  { name:'Concentration Curls', category:'isolation', muscles:['biceps'], equipment:'dumbbell', difficulty:'beginner', calPerMin:3 },

  // ── BODYWEIGHT ──────────────────────────────────────────────
  { name:'Push-Ups', category:'bodyweight', muscles:['chest','triceps','shoulders'], equipment:'none', difficulty:'beginner', calPerMin:7 },
  { name:'Pull-Ups', category:'bodyweight', muscles:['back','biceps'], equipment:'none', difficulty:'intermediate', calPerMin:8 },
  { name:'Dips', category:'bodyweight', muscles:['triceps','chest','shoulders'], equipment:'none', difficulty:'intermediate', calPerMin:7 },
  { name:'Bodyweight Squats', category:'bodyweight', muscles:['quads','glutes'], equipment:'none', difficulty:'beginner', calPerMin:6 },
  { name:'Lunges', category:'bodyweight', muscles:['quads','glutes','hamstrings'], equipment:'none', difficulty:'beginner', calPerMin:6 },
  { name:'Plank', category:'bodyweight', muscles:['core','shoulders'], equipment:'none', difficulty:'beginner', calPerMin:4 },
  { name:'Mountain Climbers', category:'bodyweight', muscles:['core','quads','shoulders'], equipment:'none', difficulty:'beginner', calPerMin:10 },
  { name:'Burpees', category:'bodyweight', muscles:['full_body'], equipment:'none', difficulty:'intermediate', calPerMin:12 },
  { name:'Glute Bridge', category:'bodyweight', muscles:['glutes','hamstrings'], equipment:'none', difficulty:'beginner', calPerMin:4 },
  { name:'Superman Hold', category:'bodyweight', muscles:['back','glutes'], equipment:'none', difficulty:'beginner', calPerMin:3 },
  { name:'Diamond Push-Ups', category:'bodyweight', muscles:['triceps','chest'], equipment:'none', difficulty:'intermediate', calPerMin:7 },
  { name:'Pike Push-Ups', category:'bodyweight', muscles:['shoulders','triceps'], equipment:'none', difficulty:'intermediate', calPerMin:6 },
  { name:'Squat Jumps', category:'bodyweight', muscles:['quads','glutes','calves'], equipment:'none', difficulty:'intermediate', calPerMin:10 },
  { name:'Inverted Rows', category:'bodyweight', muscles:['back','biceps'], equipment:'none', difficulty:'beginner', calPerMin:5 },
  { name:'Step-Ups', category:'bodyweight', muscles:['quads','glutes'], equipment:'none', difficulty:'beginner', calPerMin:6 },
  { name:'Crunches', category:'bodyweight', muscles:['core'], equipment:'none', difficulty:'beginner', calPerMin:5 },
  { name:'Leg Raises', category:'bodyweight', muscles:['core'], equipment:'none', difficulty:'intermediate', calPerMin:5 },
  { name:'Russian Twists', category:'bodyweight', muscles:['core'], equipment:'none', difficulty:'beginner', calPerMin:5 },
  { name:'Wall Sit', category:'bodyweight', muscles:['quads','glutes'], equipment:'none', difficulty:'beginner', calPerMin:4 },

  // ── CARDIO ──────────────────────────────────────────────────
  { name:'Running (moderate)', category:'cardio', muscles:['quads','calves','core'], equipment:'none', difficulty:'beginner', calPerMin:10 },
  { name:'Brisk Walking', category:'cardio', muscles:['quads','calves'], equipment:'none', difficulty:'beginner', calPerMin:5 },
  { name:'Jump Rope', category:'cardio', muscles:['calves','shoulders','core'], equipment:'none', difficulty:'beginner', calPerMin:12 },
  { name:'Cycling', category:'cardio', muscles:['quads','hamstrings','calves'], equipment:'none', difficulty:'beginner', calPerMin:8 },
  { name:'Swimming', category:'cardio', muscles:['full_body'], equipment:'none', difficulty:'intermediate', calPerMin:10 },
  { name:'Rowing Machine', category:'cardio', muscles:['back','arms','core'], equipment:'gym', difficulty:'beginner', calPerMin:9 },
  { name:'Stair Climbing', category:'cardio', muscles:['quads','glutes','calves'], equipment:'none', difficulty:'beginner', calPerMin:9 },
  { name:'Elliptical', category:'cardio', muscles:['full_body'], equipment:'gym', difficulty:'beginner', calPerMin:7 },
  { name:'Dance Workout', category:'cardio', muscles:['full_body'], equipment:'none', difficulty:'beginner', calPerMin:7 },
  { name:'Boxing (shadow)', category:'cardio', muscles:['shoulders','arms','core'], equipment:'none', difficulty:'intermediate', calPerMin:10 },
  { name:'Sprints', category:'cardio', muscles:['quads','hamstrings','glutes'], equipment:'none', difficulty:'advanced', calPerMin:14 },

  // ── HIIT ────────────────────────────────────────────────────
  { name:'Tabata Burpees', category:'hiit', muscles:['full_body'], equipment:'none', difficulty:'advanced', calPerMin:14 },
  { name:'HIIT Jump Squats', category:'hiit', muscles:['quads','glutes','calves'], equipment:'none', difficulty:'intermediate', calPerMin:12 },
  { name:'High Knees', category:'hiit', muscles:['quads','core','calves'], equipment:'none', difficulty:'beginner', calPerMin:10 },
  { name:'Battle Ropes', category:'hiit', muscles:['shoulders','arms','core'], equipment:'gym', difficulty:'intermediate', calPerMin:12 },
  { name:'Box Jumps', category:'hiit', muscles:['quads','glutes','calves'], equipment:'none', difficulty:'intermediate', calPerMin:10 },
  { name:'Kettlebell Swings', category:'hiit', muscles:['glutes','hamstrings','core'], equipment:'dumbbell', difficulty:'intermediate', calPerMin:10 },
  { name:'Tuck Jumps', category:'hiit', muscles:['quads','core','calves'], equipment:'none', difficulty:'advanced', calPerMin:12 },

  // ── FLEXIBILITY ─────────────────────────────────────────────
  { name:'Downward Dog', category:'flexibility', muscles:['hamstrings','shoulders','calves'], equipment:'none', difficulty:'beginner', calPerMin:3 },
  { name:'Pigeon Pose', category:'flexibility', muscles:['glutes','hips'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Seated Forward Fold', category:'flexibility', muscles:['hamstrings','back'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Cat-Cow Stretch', category:'flexibility', muscles:['back','core'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Warrior I Pose', category:'flexibility', muscles:['quads','shoulders','hips'], equipment:'none', difficulty:'beginner', calPerMin:3 },
  { name:'Warrior II Pose', category:'flexibility', muscles:['quads','hips','shoulders'], equipment:'none', difficulty:'beginner', calPerMin:3 },
  { name:'Child\'s Pose', category:'flexibility', muscles:['back','hips'], equipment:'none', difficulty:'beginner', calPerMin:1 },
  { name:'Hip Flexor Stretch', category:'flexibility', muscles:['hips','quads'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Hamstring Stretch', category:'flexibility', muscles:['hamstrings'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Chest Opener Stretch', category:'flexibility', muscles:['chest','shoulders'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Cobra Pose', category:'flexibility', muscles:['back','core'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Spinal Twist', category:'flexibility', muscles:['back','core'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Butterfly Stretch', category:'flexibility', muscles:['hips','inner_thighs'], equipment:'none', difficulty:'beginner', calPerMin:2 },
  { name:'Neck Stretch', category:'flexibility', muscles:['neck'], equipment:'none', difficulty:'beginner', calPerMin:1 },
  { name:'Shoulder Rolls', category:'flexibility', muscles:['shoulders'], equipment:'none', difficulty:'beginner', calPerMin:1 },
];
