// ═══════════════════════════════════════════════════════════════
// FitOptim AI — Global Food Database
// Per-serving nutritional data across 7 cuisine regions
// calories=kcal, protein/carbs/fat=grams, cost=INR, serving=grams
// ═══════════════════════════════════════════════════════════════
export const FOOD_DB = [
  // ── INDIAN ──────────────────────────────────────────────────
  { name:'Oats porridge with milk', region:'indian', type:'dairy', meals:['breakfast'], calories:220, protein:8, carbs:35, fat:5, cost:20, serving:200, unit:'ml' },
  { name:'Poha (flattened rice)', region:'indian', type:'veg', meals:['breakfast'], calories:250, protein:5, carbs:45, fat:6, cost:15, serving:200, unit:'g' },
  { name:'Upma', region:'indian', type:'veg', meals:['breakfast'], calories:230, protein:6, carbs:38, fat:7, cost:15, serving:200, unit:'g' },
  { name:'Idli (3 pcs)', region:'indian', type:'veg', meals:['breakfast'], calories:210, protein:6, carbs:40, fat:2, cost:20, serving:150, unit:'g' },
  { name:'Dosa with chutney', region:'indian', type:'veg', meals:['breakfast'], calories:280, protein:7, carbs:42, fat:9, cost:25, serving:180, unit:'g' },
  { name:'Paratha (wheat)', region:'indian', type:'veg', meals:['breakfast','lunch'], calories:260, protein:6, carbs:36, fat:10, cost:15, serving:120, unit:'g' },
  { name:'Egg bhurji (2 eggs)', region:'indian', type:'non-veg', meals:['breakfast','lunch'], calories:220, protein:14, carbs:4, fat:16, cost:20, serving:150, unit:'g' },
  { name:'Moong dal cheela', region:'indian', type:'veg', meals:['breakfast'], calories:180, protein:12, carbs:24, fat:4, cost:15, serving:150, unit:'g' },
  { name:'Roti (2 pcs)', region:'indian', type:'veg', meals:['lunch','dinner'], calories:200, protein:6, carbs:36, fat:4, cost:8, serving:120, unit:'g' },
  { name:'Steamed rice', region:'indian', type:'veg', meals:['lunch','dinner'], calories:210, protein:4, carbs:46, fat:1, cost:10, serving:180, unit:'g' },
  { name:'Dal fry (toor/moong)', region:'indian', type:'veg', meals:['lunch','dinner'], calories:180, protein:12, carbs:24, fat:4, cost:18, serving:200, unit:'ml' },
  { name:'Rajma curry', region:'indian', type:'veg', meals:['lunch','dinner'], calories:220, protein:14, carbs:30, fat:5, cost:22, serving:200, unit:'ml' },
  { name:'Chole (chickpea curry)', region:'indian', type:'veg', meals:['lunch','dinner'], calories:240, protein:12, carbs:34, fat:6, cost:22, serving:200, unit:'ml' },
  { name:'Chicken curry', region:'indian', type:'non-veg', meals:['lunch','dinner'], calories:280, protein:26, carbs:8, fat:16, cost:50, serving:200, unit:'g' },
  { name:'Fish curry', region:'indian', type:'non-veg', meals:['lunch','dinner'], calories:240, protein:24, carbs:6, fat:14, cost:55, serving:200, unit:'g' },
  { name:'Paneer bhurji', region:'indian', type:'dairy', meals:['lunch','dinner'], calories:260, protein:16, carbs:6, fat:20, cost:40, serving:150, unit:'g' },
  { name:'Palak paneer', region:'indian', type:'dairy', meals:['lunch','dinner'], calories:250, protein:14, carbs:10, fat:18, cost:40, serving:200, unit:'g' },
  { name:'Mixed veg curry', region:'indian', type:'veg', meals:['lunch','dinner'], calories:160, protein:5, carbs:18, fat:8, cost:20, serving:200, unit:'g' },
  { name:'Aloo gobi', region:'indian', type:'veg', meals:['lunch','dinner'], calories:180, protein:4, carbs:22, fat:9, cost:18, serving:200, unit:'g' },
  { name:'Raita (curd)', region:'indian', type:'dairy', meals:['lunch','dinner'], calories:80, protein:4, carbs:6, fat:4, cost:10, serving:100, unit:'ml' },
  { name:'Salad (cucumber, tomato)', region:'indian', type:'veg', meals:['lunch','dinner'], calories:40, protein:2, carbs:8, fat:0, cost:8, serving:120, unit:'g' },
  { name:'Tandoori chicken', region:'indian', type:'non-veg', meals:['lunch','dinner'], calories:260, protein:30, carbs:4, fat:14, cost:55, serving:180, unit:'g' },
  { name:'Egg curry (2 eggs)', region:'indian', type:'non-veg', meals:['lunch','dinner'], calories:260, protein:16, carbs:8, fat:18, cost:25, serving:200, unit:'g' },
  { name:'Sambar', region:'indian', type:'veg', meals:['breakfast','lunch','dinner'], calories:130, protein:6, carbs:18, fat:4, cost:15, serving:200, unit:'ml' },
  { name:'Curd rice', region:'indian', type:'dairy', meals:['lunch','dinner'], calories:250, protein:8, carbs:38, fat:6, cost:15, serving:200, unit:'g' },
  { name:'Banana (1 medium)', region:'indian', type:'veg', meals:['breakfast','snack'], calories:105, protein:1, carbs:27, fat:0, cost:5, serving:120, unit:'g' },
  { name:'Buttermilk (chaas)', region:'indian', type:'dairy', meals:['lunch','snack'], calories:45, protein:2, carbs:4, fat:2, cost:8, serving:200, unit:'ml' },
  { name:'Sprouts salad', region:'indian', type:'veg', meals:['snack','breakfast'], calories:130, protein:8, carbs:18, fat:2, cost:12, serving:100, unit:'g' },
  { name:'Roasted makhana', region:'indian', type:'veg', meals:['snack'], calories:100, protein:4, carbs:18, fat:1, cost:15, serving:30, unit:'g' },
  { name:'Chana chaat', region:'indian', type:'veg', meals:['snack'], calories:150, protein:8, carbs:22, fat:3, cost:12, serving:100, unit:'g' },
  { name:'Paneer tikka', region:'indian', type:'dairy', meals:['snack','dinner'], calories:220, protein:16, carbs:6, fat:15, cost:35, serving:120, unit:'g' },
  { name:'Lassi (sweet)', region:'indian', type:'dairy', meals:['snack','breakfast'], calories:180, protein:6, carbs:28, fat:5, cost:15, serving:250, unit:'ml' },
  { name:'Khichdi', region:'indian', type:'veg', meals:['lunch','dinner'], calories:240, protein:10, carbs:38, fat:5, cost:15, serving:250, unit:'g' },

  // ── WESTERN ─────────────────────────────────────────────────
  { name:'Scrambled eggs (3)', region:'western', type:'non-veg', meals:['breakfast'], calories:280, protein:21, carbs:3, fat:20, cost:25, serving:180, unit:'g' },
  { name:'Whole wheat toast (2 slices)', region:'western', type:'veg', meals:['breakfast','snack'], calories:160, protein:6, carbs:28, fat:2, cost:10, serving:60, unit:'g' },
  { name:'Greek yogurt', region:'western', type:'dairy', meals:['breakfast','snack'], calories:130, protein:15, carbs:8, fat:4, cost:35, serving:170, unit:'g' },
  { name:'Overnight oats', region:'western', type:'dairy', meals:['breakfast'], calories:280, protein:10, carbs:42, fat:8, cost:25, serving:250, unit:'g' },
  { name:'Avocado toast', region:'western', type:'veg', meals:['breakfast'], calories:320, protein:8, carbs:28, fat:20, cost:40, serving:200, unit:'g' },
  { name:'Protein pancakes', region:'western', type:'dairy', meals:['breakfast'], calories:300, protein:22, carbs:30, fat:10, cost:30, serving:200, unit:'g' },
  { name:'Grilled chicken breast', region:'western', type:'non-veg', meals:['lunch','dinner'], calories:250, protein:38, carbs:0, fat:10, cost:50, serving:180, unit:'g' },
  { name:'Salmon fillet', region:'western', type:'non-veg', meals:['lunch','dinner'], calories:300, protein:32, carbs:0, fat:18, cost:80, serving:180, unit:'g' },
  { name:'Turkey breast wrap', region:'western', type:'non-veg', meals:['lunch'], calories:320, protein:28, carbs:30, fat:10, cost:45, serving:250, unit:'g' },
  { name:'Caesar salad', region:'western', type:'non-veg', meals:['lunch'], calories:280, protein:18, carbs:12, fat:18, cost:40, serving:250, unit:'g' },
  { name:'Quinoa bowl', region:'western', type:'veg', meals:['lunch','dinner'], calories:260, protein:10, carbs:38, fat:8, cost:35, serving:200, unit:'g' },
  { name:'Brown rice', region:'western', type:'veg', meals:['lunch','dinner'], calories:220, protein:5, carbs:45, fat:2, cost:12, serving:185, unit:'g' },
  { name:'Sweet potato (baked)', region:'western', type:'veg', meals:['lunch','dinner','snack'], calories:160, protein:3, carbs:36, fat:0, cost:15, serving:200, unit:'g' },
  { name:'Broccoli (steamed)', region:'western', type:'veg', meals:['lunch','dinner'], calories:55, protein:4, carbs:10, fat:0, cost:12, serving:150, unit:'g' },
  { name:'Mixed green salad', region:'western', type:'veg', meals:['lunch','dinner'], calories:45, protein:2, carbs:8, fat:1, cost:15, serving:150, unit:'g' },
  { name:'Pasta (whole wheat)', region:'western', type:'veg', meals:['lunch','dinner'], calories:280, protein:10, carbs:50, fat:4, cost:18, serving:200, unit:'g' },
  { name:'Steak (lean beef)', region:'western', type:'non-veg', meals:['dinner'], calories:320, protein:36, carbs:0, fat:18, cost:90, serving:180, unit:'g' },
  { name:'Protein smoothie', region:'western', type:'dairy', meals:['breakfast','snack'], calories:220, protein:24, carbs:22, fat:4, cost:30, serving:350, unit:'ml' },
  { name:'Almonds (handful)', region:'western', type:'veg', meals:['snack'], calories:170, protein:6, carbs:6, fat:14, cost:15, serving:28, unit:'g' },
  { name:'Peanut butter (2 tbsp)', region:'western', type:'veg', meals:['snack','breakfast'], calories:190, protein:8, carbs:6, fat:16, cost:12, serving:32, unit:'g' },
  { name:'Apple (1 medium)', region:'western', type:'veg', meals:['snack'], calories:95, protein:0, carbs:25, fat:0, cost:10, serving:180, unit:'g' },
  { name:'Protein bar', region:'western', type:'dairy', meals:['snack'], calories:220, protein:20, carbs:24, fat:8, cost:40, serving:60, unit:'g' },
  { name:'Cottage cheese', region:'western', type:'dairy', meals:['snack','breakfast'], calories:110, protein:14, carbs:4, fat:4, cost:30, serving:120, unit:'g' },

  // ── MEDITERRANEAN ───────────────────────────────────────────
  { name:'Hummus with pita', region:'mediterranean', type:'veg', meals:['breakfast','snack','lunch'], calories:280, protein:10, carbs:36, fat:12, cost:25, serving:200, unit:'g' },
  { name:'Falafel (4 pcs)', region:'mediterranean', type:'veg', meals:['lunch','dinner'], calories:260, protein:12, carbs:28, fat:12, cost:30, serving:160, unit:'g' },
  { name:'Grilled halloumi', region:'mediterranean', type:'dairy', meals:['lunch','dinner','breakfast'], calories:250, protein:18, carbs:2, fat:18, cost:45, serving:120, unit:'g' },
  { name:'Tabbouleh', region:'mediterranean', type:'veg', meals:['lunch','dinner'], calories:120, protein:3, carbs:18, fat:5, cost:20, serving:150, unit:'g' },
  { name:'Shakshuka (2 eggs)', region:'mediterranean', type:'non-veg', meals:['breakfast','lunch'], calories:280, protein:16, carbs:14, fat:18, cost:30, serving:250, unit:'g' },
  { name:'Greek salad', region:'mediterranean', type:'dairy', meals:['lunch','dinner'], calories:180, protein:6, carbs:10, fat:14, cost:25, serving:200, unit:'g' },
  { name:'Grilled lamb kofta', region:'mediterranean', type:'non-veg', meals:['lunch','dinner'], calories:300, protein:24, carbs:4, fat:22, cost:60, serving:160, unit:'g' },
  { name:'Baba ganoush', region:'mediterranean', type:'veg', meals:['snack','lunch'], calories:130, protein:3, carbs:12, fat:8, cost:18, serving:100, unit:'g' },
  { name:'Labneh', region:'mediterranean', type:'dairy', meals:['breakfast','snack'], calories:100, protein:6, carbs:4, fat:7, cost:20, serving:80, unit:'g' },
  { name:'Olive oil drizzle (1 tbsp)', region:'mediterranean', type:'veg', meals:['lunch','dinner'], calories:120, protein:0, carbs:0, fat:14, cost:8, serving:14, unit:'ml' },
  { name:'Lentil soup', region:'mediterranean', type:'veg', meals:['lunch','dinner'], calories:200, protein:14, carbs:28, fat:3, cost:18, serving:250, unit:'ml' },
  { name:'Stuffed grape leaves', region:'mediterranean', type:'veg', meals:['snack','lunch'], calories:160, protein:3, carbs:20, fat:8, cost:22, serving:120, unit:'g' },
  { name:'Couscous', region:'mediterranean', type:'veg', meals:['lunch','dinner'], calories:220, protein:8, carbs:38, fat:3, cost:15, serving:180, unit:'g' },

  // ── EAST ASIAN ──────────────────────────────────────────────
  { name:'Miso soup', region:'east_asian', type:'veg', meals:['breakfast','lunch','dinner'], calories:60, protein:4, carbs:6, fat:2, cost:12, serving:200, unit:'ml' },
  { name:'Tofu stir-fry', region:'east_asian', type:'veg', meals:['lunch','dinner'], calories:200, protein:16, carbs:10, fat:12, cost:25, serving:200, unit:'g' },
  { name:'Steamed jasmine rice', region:'east_asian', type:'veg', meals:['lunch','dinner'], calories:200, protein:4, carbs:44, fat:0, cost:8, serving:180, unit:'g' },
  { name:'Chicken teriyaki', region:'east_asian', type:'non-veg', meals:['lunch','dinner'], calories:290, protein:28, carbs:16, fat:12, cost:45, serving:200, unit:'g' },
  { name:'Edamame', region:'east_asian', type:'veg', meals:['snack','lunch'], calories:120, protein:12, carbs:8, fat:5, cost:20, serving:80, unit:'g' },
  { name:'Sushi roll (6 pcs)', region:'east_asian', type:'non-veg', meals:['lunch','dinner'], calories:280, protein:12, carbs:42, fat:6, cost:50, serving:180, unit:'g' },
  { name:'Ramen noodles', region:'east_asian', type:'non-veg', meals:['lunch','dinner'], calories:400, protein:18, carbs:52, fat:14, cost:40, serving:400, unit:'ml' },
  { name:'Kimchi', region:'east_asian', type:'veg', meals:['lunch','dinner','snack'], calories:25, protein:2, carbs:4, fat:0, cost:10, serving:80, unit:'g' },
  { name:'Seaweed salad', region:'east_asian', type:'veg', meals:['lunch','dinner'], calories:50, protein:2, carbs:8, fat:1, cost:15, serving:80, unit:'g' },
  { name:'Steamed fish (soy ginger)', region:'east_asian', type:'non-veg', meals:['lunch','dinner'], calories:220, protein:28, carbs:4, fat:10, cost:55, serving:180, unit:'g' },
  { name:'Vegetable dumplings (6)', region:'east_asian', type:'veg', meals:['snack','lunch'], calories:240, protein:8, carbs:32, fat:8, cost:30, serving:150, unit:'g' },
  { name:'Congee (rice porridge)', region:'east_asian', type:'veg', meals:['breakfast'], calories:180, protein:4, carbs:36, fat:2, cost:10, serving:300, unit:'ml' },
  { name:'Green tea', region:'east_asian', type:'veg', meals:['breakfast','snack'], calories:5, protein:0, carbs:1, fat:0, cost:5, serving:200, unit:'ml' },

  // ── LATIN AMERICAN ──────────────────────────────────────────
  { name:'Black beans & rice', region:'latin', type:'veg', meals:['lunch','dinner'], calories:280, protein:14, carbs:46, fat:4, cost:15, serving:250, unit:'g' },
  { name:'Grilled chicken with chimichurri', region:'latin', type:'non-veg', meals:['lunch','dinner'], calories:280, protein:32, carbs:2, fat:16, cost:50, serving:200, unit:'g' },
  { name:'Burrito bowl', region:'latin', type:'non-veg', meals:['lunch','dinner'], calories:420, protein:24, carbs:50, fat:14, cost:45, serving:350, unit:'g' },
  { name:'Guacamole with veggies', region:'latin', type:'veg', meals:['snack'], calories:180, protein:3, carbs:12, fat:14, cost:25, serving:120, unit:'g' },
  { name:'Corn tortillas (3)', region:'latin', type:'veg', meals:['lunch','dinner'], calories:180, protein:4, carbs:34, fat:2, cost:10, serving:90, unit:'g' },
  { name:'Ceviche', region:'latin', type:'non-veg', meals:['lunch','snack'], calories:160, protein:22, carbs:8, fat:4, cost:45, serving:180, unit:'g' },
  { name:'Plantain chips', region:'latin', type:'veg', meals:['snack'], calories:180, protein:1, carbs:30, fat:7, cost:15, serving:50, unit:'g' },
  { name:'Arepa with cheese', region:'latin', type:'dairy', meals:['breakfast','snack'], calories:250, protein:8, carbs:32, fat:10, cost:20, serving:150, unit:'g' },
  { name:'Lentil & vegetable stew', region:'latin', type:'veg', meals:['lunch','dinner'], calories:220, protein:14, carbs:30, fat:4, cost:18, serving:250, unit:'g' },

  // ── AFRICAN ─────────────────────────────────────────────────
  { name:'Jollof rice', region:'african', type:'veg', meals:['lunch','dinner'], calories:300, protein:6, carbs:50, fat:8, cost:20, serving:250, unit:'g' },
  { name:'Grilled tilapia', region:'african', type:'non-veg', meals:['lunch','dinner'], calories:220, protein:30, carbs:0, fat:10, cost:45, serving:180, unit:'g' },
  { name:'Lentil stew (misir wot)', region:'african', type:'veg', meals:['lunch','dinner'], calories:200, protein:12, carbs:28, fat:5, cost:18, serving:200, unit:'g' },
  { name:'Injera (flatbread)', region:'african', type:'veg', meals:['lunch','dinner'], calories:180, protein:6, carbs:34, fat:1, cost:12, serving:120, unit:'g' },
  { name:'Groundnut soup', region:'african', type:'veg', meals:['lunch','dinner'], calories:280, protein:12, carbs:16, fat:20, cost:22, serving:250, unit:'ml' },
  { name:'Fufu with vegetables', region:'african', type:'veg', meals:['lunch','dinner'], calories:320, protein:4, carbs:60, fat:6, cost:15, serving:250, unit:'g' },
  { name:'Suya (grilled meat)', region:'african', type:'non-veg', meals:['dinner','snack'], calories:260, protein:28, carbs:4, fat:14, cost:40, serving:150, unit:'g' },
  { name:'Mandazi (2 pcs)', region:'african', type:'veg', meals:['breakfast','snack'], calories:240, protein:4, carbs:36, fat:9, cost:10, serving:100, unit:'g' },

  // ── MIDDLE EASTERN ──────────────────────────────────────────
  { name:'Shawarma plate (chicken)', region:'middle_eastern', type:'non-veg', meals:['lunch','dinner'], calories:350, protein:28, carbs:20, fat:18, cost:50, serving:250, unit:'g' },
  { name:'Fattoush salad', region:'middle_eastern', type:'veg', meals:['lunch','dinner'], calories:120, protein:3, carbs:14, fat:6, cost:18, serving:180, unit:'g' },
  { name:'Manakish (zaatar flatbread)', region:'middle_eastern', type:'veg', meals:['breakfast'], calories:280, protein:7, carbs:38, fat:11, cost:20, serving:150, unit:'g' },
  { name:'Kabsa (spiced rice)', region:'middle_eastern', type:'non-veg', meals:['lunch','dinner'], calories:380, protein:22, carbs:48, fat:12, cost:40, serving:300, unit:'g' },
  { name:'Dates (4 pcs)', region:'middle_eastern', type:'veg', meals:['snack','breakfast'], calories:110, protein:1, carbs:28, fat:0, cost:10, serving:40, unit:'g' },
  { name:'Tahini dressing (2 tbsp)', region:'middle_eastern', type:'veg', meals:['lunch','dinner'], calories:100, protein:3, carbs:3, fat:9, cost:8, serving:30, unit:'ml' },

  // ── UNIVERSAL ───────────────────────────────────────────────
  { name:'Boiled eggs (2)', region:'universal', type:'non-veg', meals:['breakfast','snack'], calories:155, protein:12, carbs:1, fat:11, cost:12, serving:100, unit:'g' },
  { name:'Milk (1 glass)', region:'universal', type:'dairy', meals:['breakfast','snack'], calories:150, protein:8, carbs:12, fat:8, cost:12, serving:250, unit:'ml' },
  { name:'Mixed nuts', region:'universal', type:'veg', meals:['snack'], calories:180, protein:6, carbs:8, fat:16, cost:20, serving:30, unit:'g' },
  { name:'Fruit bowl (seasonal)', region:'universal', type:'veg', meals:['breakfast','snack'], calories:120, protein:2, carbs:28, fat:0, cost:15, serving:200, unit:'g' },
  { name:'Whey protein shake', region:'universal', type:'dairy', meals:['snack','breakfast'], calories:120, protein:24, carbs:4, fat:1, cost:25, serving:30, unit:'g' },
  { name:'Peanuts (roasted)', region:'universal', type:'veg', meals:['snack'], calories:170, protein:7, carbs:6, fat:14, cost:8, serving:30, unit:'g' },
  { name:'Chicken soup', region:'universal', type:'non-veg', meals:['lunch','dinner'], calories:160, protein:14, carbs:12, fat:6, cost:30, serving:300, unit:'ml' },
  { name:'Vegetable soup', region:'universal', type:'veg', meals:['lunch','dinner'], calories:100, protein:4, carbs:16, fat:2, cost:15, serving:300, unit:'ml' },
  { name:'Egg white omelette', region:'universal', type:'non-veg', meals:['breakfast'], calories:110, protein:16, carbs:2, fat:4, cost:18, serving:150, unit:'g' },
  { name:'Grilled vegetables', region:'universal', type:'veg', meals:['lunch','dinner'], calories:80, protein:3, carbs:14, fat:2, cost:15, serving:180, unit:'g' },
  { name:'Chia pudding', region:'universal', type:'dairy', meals:['breakfast','snack'], calories:200, protein:6, carbs:20, fat:10, cost:25, serving:200, unit:'g' },
  { name:'Tuna salad', region:'universal', type:'non-veg', meals:['lunch','snack'], calories:200, protein:22, carbs:6, fat:10, cost:40, serving:180, unit:'g' },
  { name:'Yogurt (plain)', region:'universal', type:'dairy', meals:['breakfast','snack'], calories:100, protein:6, carbs:8, fat:5, cost:12, serving:150, unit:'g' },
  { name:'Dark chocolate (2 squares)', region:'universal', type:'veg', meals:['snack'], calories:100, protein:2, carbs:10, fat:6, cost:15, serving:20, unit:'g' },
  { name:'Orange (1 medium)', region:'universal', type:'veg', meals:['snack'], calories:65, protein:1, carbs:16, fat:0, cost:8, serving:130, unit:'g' },
  { name:'Sweet corn (boiled)', region:'universal', type:'veg', meals:['snack'], calories:110, protein:4, carbs:22, fat:2, cost:10, serving:100, unit:'g' },
];
